### ISSUE TITLE
Possible feature: auto-translation to unicode math symbols

### ISSUE THREAD

**Issue by ahelwer** [susliko/tla.nvim#1]
I've implemented this using Vim abbreviations [here](https://github.com/tlaplus-community/tlaplus-nvim-plugin) and specified the symbolic mapping in [this RFC](https://github.com/tlaplus/rfcs/issues/5).

Of course, the java tools do not accept unicode so there would have to be a conversion function available that rewrites specs into ASCII form. I have a half-finished version of such a conversion utility written [here](https://github.com/tlaplus-community/tlaplus-unicode-converter). Writing it in lua should be doable, depending on how much of the tree-sitter API is directly exposed to the lua running as a neovim plugin.

You can see a demo of this in action [here](https://www.youtube.com/watch?v=qlZQErIByWU&t=1285s).

**Comment by susliko** [comment]
Indeed, Unicode math symbols would be a nice feature to have.
I think, we shouldn't do any rewrites until tlatools support for Unicode lands, since one might want to run a checker by-hand or share a spec with someone, who uses VSCode or TLAToolbox.
Instead it could be implemented buffer-level, displaying certain sequences as unicode symbols.
This approach has already been tested by [this](https://github.com/florentc/vim-tla/blob/master/syntax/tla.vim#L168) Vim-plugin

**Comment by ahelwer** [comment]
Unfortunately displaying the symbols instead of rewriting them runs into issues with parsed alignment not matching displayed alignment in jlists - good to know about that vim plugin though, I had never seen it before!
I know Hillel Wayne has worked on [CLI wrappers for the java tools](https://github.com/hwayne/tlacli), I think in python... it's a real pain in the ass to run the java tools on the command line in my experience, so using a wrapper like his which could (with some additional work) also detect & transforms unicode before running the checker might be a lower-effort workaround, if its use were to become normalized. I have sincere doubts the java tools themselves will ever support unicode.
Anyway I opened this issue more to try to keep unicode support on the radar of any new TLA+ tools, since I do want the ecosystem to head in that direction in general.

**Comment by ahelwer** [comment]
General update on this, I've made a lot of improvements to [tlaplus-nvim-plugin](https://github.com/tlaplus-community/tlaplus-nvim-plugin) lately as part of writing a Unicode-first spec with [TLAUC](https://github.com/tlaplus-community/tlauc) translating it to ASCII for use with the tools. So things are maturing, and there is real discussion about adding Unicode to the TLA+ Java tools. Also you might enjoy attending the monthly [TLA+ community meetings](https://groups.google.com/g/tlaplus/c/CpAEnrf-DHQ/m/YrORpIfSBwAJ) (see google calendar link) if it works for your timezone! Next one on December 12th.

**Comment by ahelwer** [comment]
If people want this feature they can use the above-mentioned plugin, which is feature complete and battle tested.
