### ISSUE TITLE
Crash when JAVA_HOME is unset

### ISSUE THREAD

**Issue by dbaynard** [susliko/tla.nvim#3]
https://github.com/susliko/tla.nvim/blob/e419c75e805ab6d9967c7325bf35734c372d3d4b/lua/tla/config.lua#L5

When `JAVA_HOME` is unset, this line causes a crash in neovim 0.9, even when the `java_executable` is specified in the setup. I'm guessing there's a lazy-configuring solution? Perhaps the call to `Path:new` could be done in the setup function, rather than in the part of the `config.lua` file that is evaluated on import.

**Comment by susliko** [comment]
@dbaynard Thank you for reporting!

Here's my PR for this: https://github.com/susliko/tla.nvim/pull/4

**Comment by dbaynard** [comment]
Ah, great (my workaround was to set `JAVA_HOME`…).

If only there were some way to model this sort of thing :rofl:
